name: Upload Zipped Directory to S3
description: "A github action to copy the repo files inside a directory, zip that directory and upload to specified s3 bucket on every tag creation."
author: abdulawal39
branding:
  icon: upload-cloud
  color: purple
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Create new directory and move files
        run: >
          mkdir your-directory-name

          mv * your-directory-name/ || true  # Ignore the error when trying to move the newly created directory into itself
      - name: Archive code
        run: zip -r your-zip-file-name.zip your-directory-name/
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: >
          aws s3 cp ./your-zip-file-name.zip
          s3://$S3_BUCKET_NAME/your-zip-file-name.zip
